import React from 'react';
import type { InvoiceResponse } from '../invoice.types';
import type { BusinessSettingsResponse } from '../../settings/businessSettings.types';

interface PrintableInvoiceProps {
  invoice: InvoiceResponse;
  businessSettings?: BusinessSettingsResponse;
}

export const PrintableInvoice: React.FC<PrintableInvoiceProps> = ({
  invoice,
  businessSettings,
}) => {
  const formattedInvoiceDate = new Date(invoice.invoiceDate || invoice.createdAt).toLocaleDateString(
    'en-IN',
    {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }
  );

  const businessName = businessSettings?.businessName || 'A.S. ENTERPRISES';
  const businessPhone = businessSettings?.phone || '+91 98765 43210';
  const businessAddress =
    businessSettings?.address || 'Main Street, Commercial Complex, Maharashtra, India';
  const logoUrl = businessSettings?.logoUrl;
  const invoiceFooter =
    businessSettings?.invoiceFooter || 'Thank you for your business! This is a computer-generated tax invoice.';

  return (
    <div className="printable-invoice bg-white text-black p-8 max-w-3xl mx-auto space-y-6 font-sans text-xs border border-neutral-200">
      {/* Header Row: Business Info + Tax Invoice Title */}
      <div className="flex items-start justify-between pb-6 border-b border-neutral-300">
        <div className="space-y-1.5 max-w-sm">
          {logoUrl ? (
            <img src={logoUrl} alt={businessName} className="h-10 object-contain mb-2" />
          ) : (
            <h1 className="text-xl font-bold uppercase tracking-wider text-black">
              {businessName}
            </h1>
          )}
          <p className="text-[#333333] leading-relaxed whitespace-pre-line">{businessAddress}</p>
          <p className="text-[#333333] font-mono">Ph: {businessPhone}</p>
        </div>

        <div className="text-right space-y-1">
          <h2 className="text-lg font-extrabold uppercase tracking-widest text-neutral-800">
            TAX INVOICE
          </h2>
          <div className="font-mono text-xs text-neutral-900 pt-1">
            <p>
              <strong className="text-neutral-600">INVOICE #:</strong> {invoice.invoiceNumber}
            </p>
            <p>
              <strong className="text-neutral-600">DATE:</strong> {formattedInvoiceDate}
            </p>
            <p>
              <strong className="text-neutral-600">ORDER #:</strong> {invoice.orderNumber}
            </p>
          </div>
        </div>
      </div>

      {/* Bill To & Payment Summary Grid */}
      <div className="grid grid-cols-2 gap-6 py-2">
        <div className="space-y-1 p-3 border border-neutral-200 rounded-md bg-neutral-50/50">
          <span className="text-[10px] font-bold text-neutral-500 uppercase tracking-wider block">
            BILL TO
          </span>
          <p className="text-sm font-bold text-black">{invoice.customerNameSnapshot}</p>
          {invoice.customerPhoneSnapshot && (
            <p className="font-mono text-neutral-700">{invoice.customerPhoneSnapshot}</p>
          )}
          {invoice.customerAddressSnapshot && (
            <p className="text-neutral-700 leading-snug">{invoice.customerAddressSnapshot}</p>
          )}
        </div>

        <div className="space-y-1 p-3 border border-neutral-200 rounded-md bg-neutral-50/50 text-right">
          <span className="text-[10px] font-bold text-neutral-500 uppercase tracking-wider block">
            PAYMENT INFORMATION
          </span>
          <p className="font-semibold text-black">
            Status: <span className="uppercase text-neutral-900">{invoice.paymentStatus}</span>
          </p>
          <p className="font-mono text-neutral-700">
            Amount Received: ₹
            {(invoice.paymentReceivedAtGeneration ?? 0).toLocaleString('en-IN', {
              minimumFractionDigits: 2,
            })}
          </p>
          <p className="text-neutral-600 text-[11px]">
            Generated By: {invoice.generatedByName || 'Admin System'}
          </p>
        </div>
      </div>

      {/* Items Table */}
      <div className="pt-2">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b-2 border-neutral-800 text-neutral-600 font-bold text-[10px] uppercase tracking-wider">
              <th className="py-2.5 px-2">#</th>
              <th className="py-2.5 px-2">Item Description</th>
              <th className="py-2.5 px-2 text-right">Qty</th>
              <th className="py-2.5 px-2 text-right">Unit Price</th>
              <th className="py-2.5 px-2 text-right">Line Total</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-neutral-200 text-xs">
            {invoice.items?.map((item, idx) => (
              <tr key={item.id || idx}>
                <td className="py-2.5 px-2 font-mono text-neutral-500">{idx + 1}</td>
                <td className="py-2.5 px-2 font-medium text-black">{item.productNameSnapshot}</td>
                <td className="py-2.5 px-2 text-right font-mono text-neutral-800">{item.quantity}</td>
                <td className="py-2.5 px-2 text-right font-mono text-neutral-800">
                  ₹{item.sellingPriceSnapshot?.toFixed(2)}
                </td>
                <td className="py-2.5 px-2 text-right font-mono font-semibold text-black">
                  ₹{item.lineTotal?.toFixed(2)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Totals Breakdown */}
      <div className="flex justify-end pt-4 border-t border-neutral-300">
        <div className="w-64 space-y-1.5 font-mono text-xs">
          <div className="flex justify-between text-neutral-700">
            <span>Subtotal:</span>
            <span>₹{invoice.subtotal?.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
          </div>
          {invoice.discountAmount > 0 && (
            <div className="flex justify-between text-neutral-700">
              <span>Discount:</span>
              <span>-₹{invoice.discountAmount?.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
            </div>
          )}
          <div className="flex justify-between font-extrabold text-sm text-black pt-2 border-t-2 border-neutral-800">
            <span>TOTAL AMOUNT:</span>
            <span>₹{invoice.totalAmount?.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
          </div>
        </div>
      </div>

      {/* Terms & Footer */}
      <div className="pt-8 border-t border-neutral-300 text-center text-[10px] text-neutral-600 leading-relaxed">
        <p className="italic">{invoiceFooter}</p>
        <p className="mt-1 font-mono text-[9px] text-neutral-400">
          Invoice Reference: {invoice.invoiceNumber} · Order Reference: {invoice.orderNumber}
        </p>
      </div>
    </div>
  );
};
