package com.asenterprises.bms.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;

/**
 * Response payload generated by the Payment Suggestion Engine (FIFO Strategy).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentSuggestionResponse {

    private Long customerId;
    private String customerName;
    private BigDecimal paymentAmount;
    private BigDecimal remainingUnallocatedAmount;
    private List<SuggestedAllocationItemDto> suggestedAllocations;
}
