spring:
  application:
    name: as-enterprises-bms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8085}
  servlet:
    context-path: /api/v1

jwt:
  secret-key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 24 Hours in milliseconds (24 * 60 * 60 * 1000)

